[package]
name = "mag_encoder_firmware"
version = "0.1.0"
authors = ["Ben Scholar <bbs27@case.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.4"
cortex-m-rtic = "0.5.5"
stm32f1 = "0.11.0"
embedded-hal = "0.2.3"
nb = "1.0.0"
volatile = "0.3.0"
heapless = "0.5.6"
bxcan = ""

[dependencies.stm32f1xx-hal]
version = "0.7.0"
features = ["stm32f103", "rt"]

[patch.crates-io]
stm32f1xx-hal = { git = "https://github.com/timokroeger/stm32f1xx-hal", branch="bxcan", features = ["stm32f103", "rt", "stm32-usbd"] }

[[bin]]
name = "mag_encoder_firmware"
test = false
bench = false

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 'z'
