[package]
name = "mag_encoder_firmware"
version = "0.1.0"
authors = ["Ben Scholar <bbs27@case.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.4"
cortex-m-rtic = "0.5.5"
stm32f1 = "0.11.0"
embedded-hal = "0.2.3"
nb = "1.0.0"
volatile = "0.3.0"
heapless = "0.5.6"
bxcan = "0.2.3"
num-traits = { version="0.2.14", default-features = false }

[dependencies.stm32f1xx-hal]
version = ""
features = ["stm32f103", "rt", "stm32-usbd"] 

[patch.crates-io]
stm32f1xx-hal = { git = "https://github.com/timokroeger/stm32f1xx-hal", branch="bxcan", features = ["stm32f103", "rt", "stm32-usbd", "has-can"] }
bxcan = {git = "https://github.com/stm32-rs/bxcan" }

[[bin]]
name = "mag_encoder_firmware"
test = false
bench = false

[profile.dev]
lto = true
opt-level = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 2
