on: [push]

name: CI

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: thumbv7m-none-eabi
      - name: Build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: thumbv7m-none-eabi
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  check:
    name: Check format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: thumbv7m-none-eabi
          components: rustfmt, clippy
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

