on: [push]

name: CI

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: thumbv7m-none-eabi
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
